Added dirsync to requirements.txt Refactored source update's to sync and purge files that no longer exist Added checksum generator and validator to help maintain file integrity of project Fixed #SICKRAGE-APP-5Q6 - AttributeError in sickrage.core.version_updater in update method, 'NoneType' object has no attribute 'content' Added fix for dupe scene absolute numbering Fixed #SICKRAGE-APP-5R0 - AttributeError in sickrage.providers.torrent.extratorrent