Issue with requests lib on debian AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3' Debian no longer includes this method by default.  I have patched the file to allow it to start without.  Updating requests will fix this as well